package it.sgdc3.smartstorage.registry

import it.sgdc3.smartstorage.SmartStorage.guiTexture
import xyz.xenondevs.nova.initialize.Init
import xyz.xenondevs.nova.initialize.InitStage

/**
 * Menu backgrounds.
 *
 * Nova draws these over the vanilla container texture, which is what stops every menu from looking
 * like a chest. The PNGs are generated by `tools/gen-gui-textures.ps1` from Nova's own
 * `vanilla/generic_9xN` textures, so the panel, player inventory and hotbar stay pixel-identical to
 * the rest of Nova and only the upper slot grid is ours.
 */
@Init(stage = InitStage.PRE_PACK)
object GuiTextures {

    val STORAGE_TERMINAL = guiTexture("storage_terminal") { path("gui/storage_terminal") }
    val CRAFTING_TERMINAL = guiTexture("crafting_terminal") { path("gui/crafting_terminal") }
    val FLUID_TERMINAL = guiTexture("fluid_terminal") { path("gui/fluid_terminal") }

    /**
     * The wireless terminal's own list, which is the storage terminal's without the deposit row: an item
     * you carry has nowhere to park what it cannot store.
     */
    val WIRELESS_TERMINAL = guiTexture("wireless_terminal") { path("gui/wireless_terminal") }
    val WIRELESS_CRAFTING = guiTexture("wireless_crafting") { path("gui/wireless_crafting") }
    val WIRELESS_UPGRADES = guiTexture("wireless_upgrades") { path("gui/wireless_upgrades") }
    val WIRELESS_ACCESS_POINT = guiTexture("wireless_access_point") { path("gui/wireless_access_point") }
    val STORAGE_CONTROLLER = guiTexture("storage_controller") { path("gui/storage_controller") }
    val DRIVE_BAY = guiTexture("drive_bay") { path("gui/drive_bay") }
    val STORAGE_INTERFACE = guiTexture("storage_interface") { path("gui/storage_interface") }
    val STORAGE_CONNECTOR = guiTexture("storage_connector") { path("gui/storage_connector") }
    /**
     * The one-side menu a storage interface port opens. Its own texture rather than the interface's,
     * because that one draws two filter slots this menu has nothing to put in.
     */
    val INTERFACE_SIDE = guiTexture("interface_side") { path("gui/interface_side") }

    val STORAGE_BARREL = guiTexture("storage_barrel") { path("gui/storage_barrel") }
    val BARREL_CONTROLLER = guiTexture("barrel_controller") { path("gui/barrel_controller") }

}
